name: Backup Automation

on: 
  repository_dispatch:
    types: [run_backup]

jobs: 
  backup_test:
    runs-on: ubuntu-latest
    
    steps: 

      - name: Check out repository code
        uses: actions/checkout@v4

    
      - name: Run Backup Script
        run: ./backup_avan
